---
name: Vultr Deployment

on:
  push:
    branches:
      - master
      - develop

env:
  DEPLOYMENT_FILE: das-function.yml

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    environment: develop
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup OpenFaaS
        run: curl -sSL https://cli.openfaas.com | sudo -E sh

      - name: Login to OpenFaaS Gateway
        run: faas-cli login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} -g ${{ secrets.OPENFAAS_GATEWAY }}

      - name: Pull template
        run: faas-cli template pull https://github.com/singnet/das-openfaas-templates

      - name: Deploy the function
        run: |-
          FAAS_GATEWAY=${{ secrets.OPENFAAS_GATEWAY }} \
          DAS_MONGODB_HOSTNAME=${{secrets.DAS_MONGODB_HOSTNAME}} \
          DAS_MONGODB_PORT=${{secrets.DAS_MONGODB_PORT}} \
          DAS_MONGODB_USERNAME=${{secrets.DAS_MONGODB_USERNAME}} \
          DAS_MONGODB_PASSWORD=${{secrets.DAS_MONGODB_PASSWORD}} \
          DAS_MONGODB_NAME=${{secrets.DAS_MONGODB_NAME}} \
          DAS_REDIS_HOSTNAME=${{secrets.DAS_REDIS_HOSTNAME}} \
          DAS_REDIS_PORT=${{secrets.DAS_REDIS_PORT}} \
          faas-cli deploy -f ${{ env.DEPLOYMENT_FILE }}

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/master'
    env:
      DEPLOYMENT_FILE: das-function.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup OpenFaaS
        run: curl -sSL https://cli.openfaas.com | sudo -E sh

      - name: Login to OpenFaaS Gateway
        run: faas-cli login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} -g ${{ secrets.OPENFAAS_GATEWAY }}

      - name: Pull template
        run: faas-cli template pull https://github.com/singnet/das-openfaas-templates

      - name: Deploy the function
        run: |-
          FAAS_GATEWAY=${{ secrets.OPENFAAS_GATEWAY }} \
          DAS_MONGODB_HOSTNAME=${{secrets.DAS_MONGODB_HOSTNAME}} \
          DAS_MONGODB_PORT=${{secrets.DAS_MONGODB_PORT}} \
          DAS_MONGODB_USERNAME=${{secrets.DAS_MONGODB_USERNAME}} \
          DAS_MONGODB_PASSWORD=${{secrets.DAS_MONGODB_PASSWORD}} \
          DAS_MONGODB_NAME=${{secrets.DAS_MONGODB_NAME}} \
          DAS_REDIS_HOSTNAME=${{secrets.DAS_REDIS_HOSTNAME}} \
          DAS_REDIS_PORT=${{secrets.DAS_REDIS_PORT}} \
          faas-cli deploy -f ${{ env.DEPLOYMENT_FILE }}
